apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-blackbox-exporter-config-map
  namespace: monitoring
  labels:
    app: prometheus-blackbox-exporter
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        http:
          preferred_ip_protocol: ip4
        prober: http
        timeout: 60s
