version: '3'
services:
  myapp:
    image: linux_tweet_app-image
  myproxy:
    container_name: myproxy
    image: myproxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/ssl:/etc/nginx/certs
