apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 5Gi
  hostPath:
    path: /mysql-statefulsets
